application: hobyn-trbl
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /secure_api/.*
  script: api_handler.app
  login: required
  auth_fail_action: unauthorized

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: main.app
  secure: always
- url: /all_hobbies
  script: main.app
- url: /personal_hobby
  script: main.app
- url: .*
  script: main.app
  login: required
#- url: /admin/.*
  #script: main.app
  #login: admin

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
